apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-service
spec:
  template:
    spec:
      containers:
      - name: hello-service
        image: image-registry.openshift-image-registry.svc:5000/hello-dev/hello-service:prod-2022-07-27-02-00-23
